# Book settings
title: FD and Spectral methods for PDE
author: Tobin A. Driscoll
# logo: 
copyright: "2022"

exclude_patterns: 
  - etc/*.ipynb

parse:
  myst_enable_extensions:
  - amsmath
  - colon_fence
  - deflist
  - dollarmath
  - html_image
  - linkify
#  - replacements

kernelspec:
  name: julia-1.8
  display_name: Julia 1.8
  language: julia

latex:
  latex_documents:
    targetname: fdspec.tex
  latex_engine: xelatex

execute:
  execute_notebooks: cache
  timeout: 250
  allow_errors: true
  run_in_temp: false

html:
  # favicon: favicon.ico
  extra_footer: "<img alt='UD logo' src='_static/UDlogo-small.png'>"
  # google_analytics_id: UA-172898555-1

sphinx:
  config:
    numfig_secnum_depth: 2
    # pygments_style: fnc
    mathjax3_config:
      tex:
        macros:
          "float": ["\\mathbb{F}"]
          "real": ["\\mathbb{R}"]
          "complex": ["\\mathbb{C}"]
          "nat": ["\\mathbb{N}"]
          "integer": ["\\mathbb{Z}"]
          "bfa" : "\\mathbf{a}"
          "bfb" : "\\mathbf{b}"
          "bfe" : "\\mathbf{e}"
          "bff" : "\\mathbf{f}"
          "bfx" : "\\mathbf{x}"
          "bfX" : "\\mathbf{X}"
          "bfA" : "\\mathbf{A}"
          "bfD" : "\\mathbf{D}"
          "bfJ" : "\\mathbf{J}"
          "bfC" : "\\mathbf{C}"
          "bfP" : "\\mathbf{P}"
          "bfQ" : "\\mathbf{Q}"
          "bfW" : "\\mathbf{W}"
          "bfp" : "\\mathbf{p}"
          "bfs" : "\\mathbf{s}"
          "bfu" : "\\mathbf{u}"
          "bfv" : "\\mathbf{v}"
          "bfw" : "\\mathbf{w}"
          "bfy" : "\\mathbf{y}"
          "bfz" : "\\mathbf{z}"
          "bfzero" : "\\boldsymbol{0}"
          "bfmu" : "\\boldsymbol{\\mu}"
          "bftau" : "\\boldsymbol{\\tau}"
          "TP" : "\\text{TP}"
          "TN" : "\\text{TN}"
          "FP" : "\\text{FP}"
          "FN" : "\\text{FN}"
          "rmn" : ["\\mathbb{R}^{#1 \\times #2}",2]
          "dd" : ["\\frac{d #1}{d #2}",2]
          "pp" : ["\\frac{\\partial #1}{\\partial #2}",2]
          "norm" : ["\\left\\lVert \\mathstrut #1 \\right\\rVert",1]
          "abs" : ["\\left\\lvert \\mathstrut #1 \\right\\rvert",1]
          "twonorm" : ["\\norm{#1}_2",1]
          "onenorm" : ["\\norm{#1}_1",1]
          "infnorm" : ["\\norm{#1}_\\infty",1]
          "inprod" : ["\\langle #1,#2 \\rangle",2]
          "pr" : ["^{(#1)}",1]
          "diag": ["\\operatorname{diag}"]
          "sign": ["\\operatorname{sign}"]
          "dist": ["\\operatorname{dist}"]
          "simil": ["\\operatorname{sim}"]
          "ee": ["\\times 10^"]
          "floor": ["\\lfloor#1\\rfloor",1]
          "argmin": ["\\operatorname{argmin}"]
          "epsm": ["\\varepsilon_\\text{mach}"]
          "logit": ["\\operatorname{logit}"]
    
    latex_additional_files: etc/preamble.tex
    latex_elements:
      preamble: >
        \usepackage{mathtools}
        \usepackage{fontspec}
        \usepackage{unicode-math}
        \setmainfont[Ligatures=TeX]{TeX Gyre Schola}
        \setmathfont{TeX Gyre Schola Math}
        \include{preamble}
      passoptionstopackages: \PassOptionsToPackage{svgnames}{xcolor}
      sphinxsetup: verbatimwithframe=false,VerbatimColor={RGB}{255,252,245}

  extra_extensions:
  - sphinx_proof
  # - sphinx_jupyterbook_latex

# Information about where the book exists on the web
repository:
  url                       : https://github.com/tobydriscoll/fd-spectral-notes # Online location of your book
  # book_path                 : notes  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  notebook-interface: "classic"
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
  thebe: true